### ISSUE TITLE
Got an error when running your code

### ISSUE THREAD

**Issue by yuz79** [Jakaria08/EESRGAN#10]
Hello,
I got an error when running the train.py:
Traceback (most recent call last):
  File "train.py", line 94, in <module>
    main(config)
  File "train.py", line 32, in main
    screen=True, tofile=True)
  File "C:\EESRGAN\utils\util.py", line 328, in setup_logger
    fh = logging.FileHandler(log_file, mode='w')
  File "C:\MIMIA\Anaconda3\envs\tensorflow\lib\logging\__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\MIMIA\Anaconda3\envs\tensorflow\lib\logging\__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\EESRGAN\\saved\\logs\\train_RRDB_ESRGANx4_200730-145122.log

Would you please tell me what is going wrong？ Thank you!

**Comment by rileymjohnson** [comment]
You need to create a `logs` directory inside the save folder. It is trying to write into a directory that doesn't exist.
