### ISSUE TITLE
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

### ISSUE THREAD

**Issue by anubhav1997** [Jakaria08/EESRGAN#13]
Hi, 

I am trying to run the test script using the following command: 

python test.py -c config_GAN.json

I get the below error, could you please help me out? 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 96, in <module>
    main(config)
  File "test.py", line 19, in main
    tester.test()
  File "/home/jovyan/EESRGAN/trainer/cowc_GAN_FRCNN_trainer.py", line 38, in test
    self.model.test(self.data_loader, train=False, testResult=True)
  File "/home/jovyan/EESRGAN/model/ESRGAN_EESN_FRCNN_Model.py", line 272, in test
    evaluate(self.netG, self.netFRCNN, self.targets, self.device)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/jovyan/EESRGAN/detection/engine.py", line 142, in evaluate
    coco_evaluator = CocoEvaluator(coco, iou_types)
  File "/home/jovyan/EESRGAN/detection/coco_eval.py", line 28, in __init__
    self.coco_eval[iou_type] = COCOeval(coco_gt, iouType=iou_type)
  File "/opt/conda/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
  File "/opt/conda/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 527, in __init__
    self.setDetParams()
  File "/opt/conda/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 6, in linspace
  File "/opt/conda/lib/python3.7/site-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

**Comment by anubhav1997** [comment]
https://stackoverflow.com/questions/59493606/pytorch-and-tensorflow-object-detection-evaluate-object-of-type-class-nump

It's due to a numpy version issue.
