### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by bostankhan6** [Jakaria08/EESRGAN#23]
I am getting the following problem while training in colab:

Traceback (most recent call last):
  File "train.py", line 94, in <module>
    main(config)
  File "train.py", line 73, in main
    trainer.train()
  File "/content/EESRGAN/trainer/cowc_GAN_FRCNN_trainer.py", line 83, in train
    self.model.optimize_parameters(current_step)
  File "/content/EESRGAN/model/ESRGAN_EESN_FRCNN_Model.py", line 196, in optimize_parameters
    l_g_total.backward(retain_graph=True)
  File "/usr/local/lib/python3.7/dist-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

Please help!

**Comment by CQBen** [comment]
I also facing the same question, have you guys solved it?

**Comment by CQBen** [comment]
> I am getting the following problem while training in colab:
> 
> Traceback (most recent call last): File "train.py", line 94, in main(config) File "train.py", line 73, in main trainer.train() File "/content/EESRGAN/trainer/cowc_GAN_FRCNN_trainer.py", line 83, in train self.model.optimize_parameters(current_step) File "/content/EESRGAN/model/ESRGAN_EESN_FRCNN_Model.py", line 196, in optimize_parameters l_g_total.backward(retain_graph=True) File "/usr/local/lib/python3.7/dist-packages/torch/tensor.py", line 107, in backward torch.autograd.backward(self, gradient, retain_graph, create_graph) File "/usr/local/lib/python3.7/dist-packages/torch/autograd/**init**.py", line 93, in backward allow_unreachable=True) # allow_unreachable flag RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
> 
> Please help!

I also facing the same question, have you guys solved it?
