### ISSUE TITLE
RuntimeError: A view was created in no_grad mode and is being modified inplace with grad mode enabled. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one

### ISSUE THREAD

**Issue by rutuja1409** [Jakaria08/EESRGAN#25]
Hello @Jakaria08  I'm getting this error. Can you help me solve this ?

21-05-02 10:35:50.553 - INFO: Total epochs needed: 736 for iters 400,000
2021-05-02 10:35:50.717038: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
21-05-02 10:35:51.840 - INFO: Start training from epoch: 0, iter: 0
Traceback (most recent call last):
  File "/content/drive/MyDrive/Project/EESRGAN/train.py", line 94, in <module>
    main(config)
  File "/content/drive/MyDrive/Project/EESRGAN/train.py", line 73, in main
    trainer.train()
  File "/content/drive/MyDrive/Project/EESRGAN/trainer/cowc_GAN_FRCNN_trainer.py", line 83, in train
    self.model.optimize_parameters(current_step)
  File "/content/drive/MyDrive/Project/EESRGAN/model/ESRGAN_EESN_FRCNN_Model.py", line 234, in optimize_parameters
    loss_dict = self.netFRCNN(self.intermediate_img, self.targets)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/models/detection/generalized_rcnn.py", line 78, in forward
    images, targets = self.transform(images, targets)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/models/detection/transform.py", line 110, in forward
    images = self.batch_images(images)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/models/detection/transform.py", line 215, in batch_images
    pad_img[: img.shape[0], : img.shape[1], : img.shape[2]].copy_(img)

Above is the error i'm getting. Can you help me ?

**Comment by Githopp** [comment]
For me Pytorch 1.1.0 solved these error (check requirements.txt).

**Comment by KZGSK** [comment]
@rutuja1409  Were you able to fix this issue? I'm getting the same error.

**Comment by YanADingggg** [comment]
Hello, may I ask if you have solved this problem? Now I have the same problem and I would like to ask for help. Thank you very much @weichen5926 @rutuja1409 @Githopp

**Comment by KZGSK** [comment]
Hi, I'm sorry to reply you so late.I think it's a Pytorch version problem. For me Pytorch1.2 and 1.10 solved these error. But,you can change "self.intermediate_img = self.final_SR" to“self.intermediate_img = self.final_SR.detach()”.In this way, no error can be reported,but there may be potential problems.I didn't continue to verify. Good luck！ @YanADingggg

**Comment by apolc123** [comment]
> 你好，很抱歉这么晚才回复你，我觉得是Pytorch版本的问题，我使用Pytorch1.2和1.10解决了这个问题，不过你可以把“self.intermediate_img = self.final_SR”改成“self.intermediate_img = self.final_SR.detach()”，这样就不会报错，但是可能会有潜在的问题，我没有继续验证，祝你好运！@YanADingggg

非常感谢，解决了，找了一天bug了
